-- Seed 50+ RSS sources (run after schema). Idempotent: uses ON CONFLICT DO NOTHING on slug.
INSERT INTO sources (name, slug, type, url, category, language) VALUES
('BBC News', 'bbc-news', 'rss', 'https://feeds.bbci.co.uk/news/rss.xml', 'General', 'en'),
('Reuters', 'reuters', 'rss', 'https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best', 'General', 'en'),
('The Guardian', 'the-guardian', 'rss', 'https://www.theguardian.com/world/rss', 'World', 'en'),
('AP News', 'ap-news', 'rss', 'https://feeds.apnews.com/rss/topnews', 'General', 'en'),
('NPR', 'npr', 'rss', 'https://feeds.npr.org/1001/rss.xml', 'General', 'en'),
('CNN', 'cnn', 'rss', 'https://rss.cnn.com/rss/cnn_topstories.rss', 'General', 'en'),
('Al Jazeera', 'al-jazeera', 'rss', 'https://www.aljazeera.com/xml/rss/all.xml', 'General', 'en'),
('NBC News', 'nbc-news', 'rss', 'https://feeds.nbcnews.com/nbcnews/public/news', 'General', 'en'),
('CBS News', 'cbs-news', 'rss', 'https://www.cbsnews.com/latest/rss/main', 'General', 'en'),
('ABC News', 'abc-news', 'rss', 'https://abcnews.go.com/abcnews/topstories', 'General', 'en'),
('PBS NewsHour', 'pbs-newshour', 'rss', 'https://www.pbs.org/newshour/feeds/rss/headlines', 'General', 'en'),
('USA Today', 'usa-today', 'rss', 'https://rssfeeds.usatoday.com/usatoday-NewsTopStories', 'General', 'en'),
('Los Angeles Times', 'la-times', 'rss', 'https://www.latimes.com/california/rss2.0.xml', 'Regional', 'en'),
('Washington Post', 'washington-post', 'rss', 'https://feeds.washingtonpost.com/rss/world', 'World', 'en'),
('New York Times', 'nytimes', 'rss', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'World', 'en'),
('Wall Street Journal', 'wsj', 'rss', 'https://feeds.content.dowjones.io/public/rss/nyt_topstories', 'Business', 'en'),
('Bloomberg', 'bloomberg', 'rss', 'https://feeds.bloomberg.com/markets/news.rss', 'Business', 'en'),
('CNBC', 'cnbc', 'rss', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'Business', 'en'),
('TechCrunch', 'techcrunch', 'rss', 'https://techcrunch.com/feed/', 'Technology', 'en'),
('The Verge', 'the-verge', 'rss', 'https://www.theverge.com/rss/index.xml', 'Technology', 'en'),
('Ars Technica', 'ars-technica', 'rss', 'https://feeds.arstechnica.com/arstechnica/index', 'Technology', 'en'),
('Wired', 'wired', 'rss', 'https://www.wired.com/feed/rss', 'Technology', 'en'),
('Mashable', 'mashable', 'rss', 'https://mashable.com/feed/', 'Technology', 'en'),
('Engadget', 'engadget', 'rss', 'https://www.engadget.com/rss.xml', 'Technology', 'en'),
('Gizmodo', 'gizmodo', 'rss', 'https://gizmodo.com/rss', 'Technology', 'en'),
('Recode', 'recode', 'rss', 'https://www.vox.com/rss/recode/index.xml', 'Technology', 'en'),
('Nature', 'nature', 'rss', 'https://www.nature.com/nature.rss', 'Science', 'en'),
('Science Daily', 'science-daily', 'rss', 'https://www.sciencedaily.com/rss/all.xml', 'Science', 'en'),
('Scientific American', 'scientific-american', 'rss', 'https://rss.sciam.com/ScientificAmerican-Global', 'Science', 'en'),
('ESPN', 'espn', 'rss', 'https://www.espn.com/espn/rss/news', 'Sports', 'en'),
('BBC Sport', 'bbc-sport', 'rss', 'https://feeds.bbci.co.uk/sport/rss.xml', 'Sports', 'en'),
('The Athletic', 'the-athletic', 'rss', 'https://theathletic.com/feed/', 'Sports', 'en'),
('Politico', 'politico', 'rss', 'https://www.politico.com/rss/politics08.xml', 'Politics', 'en'),
('Axios', 'axios', 'rss', 'https://api.axios.com/feed/', 'Politics', 'en'),
('Vox', 'vox', 'rss', 'https://www.vox.com/rss/index.xml', 'General', 'en'),
('Slate', 'slate', 'rss', 'https://slate.com/feeds/all.rss', 'General', 'en'),
('Vice', 'vice', 'rss', 'https://www.vice.com/en/rss', 'General', 'en'),
('HuffPost', 'huffpost', 'rss', 'https://www.huffpost.com/section/front-page/feed', 'General', 'en'),
('ProPublica', 'propublica', 'rss', 'https://www.propublica.org/feeds/propublica/main', 'Investigative', 'en'),
('The Hill', 'the-hill', 'rss', 'https://thehill.com/feed/', 'Politics', 'en'),
('NPR Politics', 'npr-politics', 'rss', 'https://feeds.npr.org/1014/rss.xml', 'Politics', 'en'),
('Reuters Business', 'reuters-business', 'rss', 'https://www.reutersagency.com/feed/?best-topics=business-finance', 'Business', 'en'),
('Reuters Tech', 'reuters-tech', 'rss', 'https://www.reutersagency.com/feed/?best-topics=tech', 'Technology', 'en'),
('MIT Technology Review', 'mit-tech-review', 'rss', 'https://www.technologyreview.com/feed/', 'Technology', 'en'),
('Harvard Business Review', 'hbr', 'rss', 'https://hbr.org/feed', 'Business', 'en'),
('Economist', 'economist', 'rss', 'https://www.economist.com/weeklyedition/rss.xml', 'Business', 'en'),
('Foreign Affairs', 'foreign-affairs', 'rss', 'https://www.foreignaffairs.com/rss.xml', 'World', 'en'),
('Foreign Policy', 'foreign-policy', 'rss', 'https://foreignpolicy.com/feed/', 'World', 'en'),
('Defense One', 'defense-one', 'rss', 'https://www.defenseone.com/rss/', 'Defense', 'en'),
('Rolling Stone', 'rolling-stone', 'rss', 'https://www.rollingstone.com/feed/', 'Culture', 'en'),
('Variety', 'variety', 'rss', 'https://variety.com/feed/', 'Entertainment', 'en'),
('Hollywood Reporter', 'hollywood-reporter', 'rss', 'https://www.hollywoodreporter.com/feed/', 'Entertainment', 'en'),
('IGN', 'ign', 'rss', 'https://feeds.feedburner.com/ign/all', 'Gaming', 'en'),
('Polygon', 'polygon', 'rss', 'https://www.polygon.com/rss/index.xml', 'Gaming', 'en'),
('Kotaku', 'kotaku', 'rss', 'https://kotaku.com/rss', 'Gaming', 'en'),
('Lifehacker', 'lifehacker', 'rss', 'https://lifehacker.com/rss', 'Lifestyle', 'en')
ON CONFLICT (slug) DO NOTHING;
